apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  pierwszyklucz-lubiacy-values: "{{ .Values.ala }}"
  drugiklucz-lubiacy-releases: "{{ .Release.Name }}"
  trzeci-lubi-charty: "{{ .Chart.Name }}"
