apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  key01-based-on-values: "{{ .Values.ala }}"
  key02-based-on-releases: "{{ .Release.Name }}"
  key03-based-on-charts: "{{ .Chart.Name }}"
