apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  key01-basedon-values: "{{ .Values.ala }}"
  key02-basedon-releases: "{{ .Release.Name }}"
  key03-basedon--charts: "{{ .Chart.Name }}"
