apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.label }}
  name: {{ .Release.Name }}
  namespace: namespace55
spec:
  ports:
  - port: {{ .Values.servicePort }}
    name: http
    protocol: {{ .Values.PROTO }}
    targetPort: {{ .Values.targetPort }}
  selector:
    app: {{ .Values.label }}
  sessionAffinity: None
  type: ClusterIP
